# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agriculture
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: flask_app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://thiago:root@db/agriculture
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  postgres_data:
